#!/usr/bin/env python
import random
with open("asciimap", "r") as f:
    data = f.readlines()
offending_colors = ["31;1", "31", "33", "33;1"] + ["33;1"] * 10
defending_colors = ["32", "35", "36", "34;1"] + ["32"]*10
string = "\033c"
for line in data:
    for ch in line:
        if ch == ".": ch = " "
        if ch in "abcdefghijklmnopqrstuvwxyz":
            color = random.choice(offending_colors)
            string += "\033[{}m{}\033[0m".format(color, ch)
        elif ch in "~!@$%^&*()+=-_":
            color = random.choice(defending_colors)
            string += "\033[{}m{}\033[0m".format(color, ch)
        else: string += ch
#        string += " "
print(string)
print("\033[0m")
